//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingTracker.DAL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedbackType
    {
        public FeedbackType()
        {
            this.Feedbacks = new HashSet<Feedback>();
        }
    
        public int FeedbackTypeId { get; set; }
        public string Description { get; set; }
        public Nullable<int> Sequence { get; set; }
    
        public virtual ICollection<Feedback> Feedbacks { get; set; }
    }
}
