//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingTracker.DAL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int FeedbackId { get; set; }
        public string FeedbackText { get; set; }
        public string Title { get; set; }
        public Nullable<int> FeedbackType { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> SkillId { get; set; }
        public Nullable<short> Rating { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<int> AddedFor { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual FeedbackType FeedbackType1 { get; set; }
    }
}
