//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingTracker.DAL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public Notification()
        {
            this.UserNotificationMappings = new HashSet<UserNotificationMapping>();
        }
    
        public int NotificationId { get; set; }
        public string NotificationTitle { get; set; }
        public string Description { get; set; }
        public string Link { get; set; }
        public int NotificationType { get; set; }
        public int AddedBy { get; set; }
        public System.DateTime AddedOn { get; set; }
    
        public virtual ICollection<UserNotificationMapping> UserNotificationMappings { get; set; }
        public virtual NotificationType NotificationType1 { get; set; }
        public virtual User User { get; set; }
    }
}
