//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingTracker.DAL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionLevelMapping
    {
        public int Id { get; set; }
        public int QuestionId { get; set; }
        public short Level { get; set; }
        public short ExperienceStartRange { get; set; }
        public short ExperienceEndRange { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
