//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingTracker.DAL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyResponse
    {
        public int SurveyResponse1 { get; set; }
        public int SurveyQuestionId { get; set; }
        public Nullable<int> SurveyAnswerId { get; set; }
        public string AdditionalNote { get; set; }
        public int SurveyCompletedMetaDataId { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual SurveyAnswer SurveyAnswer { get; set; }
        public virtual SurveyCompletedMetaData SurveyCompletedMetaData { get; set; }
        public virtual SurveyQuestion SurveyQuestion { get; set; }
    }
}
