//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingTracker.DAL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyQuestion
    {
        public SurveyQuestion()
        {
            this.SurveyAnswers = new HashSet<SurveyAnswer>();
            this.SurveyResponses = new HashSet<SurveyResponse>();
        }
    
        public int SurveyQuestionId { get; set; }
        public int SurveySectionId { get; set; }
        public string QuestionText { get; set; }
        public string HelpText { get; set; }
        public bool IsMandatory { get; set; }
        public bool AdditionalNoteRequired { get; set; }
        public int ResponseTypeId { get; set; }
        public bool IsDeleted { get; set; }
        public int SortOrder { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual ICollection<SurveyAnswer> SurveyAnswers { get; set; }
        public virtual SurveyQuestionResponseType SurveyQuestionResponseType { get; set; }
        public virtual SurveySection SurveySection { get; set; }
        public virtual ICollection<SurveyResponse> SurveyResponses { get; set; }
    }
}
