//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingTracker.DAL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyQuestionResponseType
    {
        public SurveyQuestionResponseType()
        {
            this.SurveyQuestions = new HashSet<SurveyQuestion>();
        }
    
        public int TypeId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<SurveyQuestion> SurveyQuestions { get; set; }
    }
}
