//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingTracker.DAL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyCompletedMetaData
    {
        public SurveyCompletedMetaData()
        {
            this.SurveyResponses = new HashSet<SurveyResponse>();
            this.WeeklyFeedbackSurveyMappings = new HashSet<WeeklyFeedbackSurveyMapping>();
        }
    
        public int SurveyCompletedMetaDataId { get; set; }
        public int SurveyId { get; set; }
        public System.DateTime DateCompleted { get; set; }
        public int SurveyTakenBy { get; set; }
    
        public virtual Survey Survey { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<SurveyResponse> SurveyResponses { get; set; }
        public virtual ICollection<WeeklyFeedbackSurveyMapping> WeeklyFeedbackSurveyMappings { get; set; }
    }
}
