//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingTracker.DAL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveySection
    {
        public SurveySection()
        {
            this.SurveyQuestions = new HashSet<SurveyQuestion>();
        }
    
        public int SurveySectionId { get; set; }
        public string SectionHeader { get; set; }
        public int SortOrder { get; set; }
        public int SurveyId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Survey Survey { get; set; }
        public virtual ICollection<SurveyQuestion> SurveyQuestions { get; set; }
    }
}
