//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingTracker.DAL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public Team()
        {
            this.Users = new HashSet<User>();
        }
    
        public int TeamId { get; set; }
        public string TeamName { get; set; }
        public int TeamManager { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime DateInserted { get; set; }
        public int WeeklySurveyId { get; set; }
    
        public virtual Survey Survey { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual User User { get; set; }
    }
}
