//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingTracker.DAL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeeklyFeedbackSurveyMapping
    {
        public int Id { get; set; }
        public int FeedbackId { get; set; }
        public int SurveyCompletedMetaDataId { get; set; }
    
        public virtual Feedback Feedback { get; set; }
        public virtual SurveyCompletedMetaData SurveyCompletedMetaData { get; set; }
    }
}
